### ISSUE TITLE
Vmware.pm

### ISSUE THREAD

**Issue by bebozps** [PluginsOCSInventory-NG/vmware-vcenter#10]
Dear,

I'd like to know where to put a Vmware.pm file under OCS server? any instruction it's really appreciate

best regards,
A\

**Comment by 0XD1B** [comment]
Hello @bebozps, if you're still looking about this information, i had to place it down here : /usr/share/perl5/vendor_perl/Ocsinventory/Agent/Modules/Vmware.pm.

Regards.

**Comment by fbomj** [comment]
Hi
Depending of the Linux distribution you have to put Vmware.pm in :

- /usr/local/share/perl5/Ocsinventory/Agent/Modules for CentOS/RedHat/Fedora
- /usr/local/share/perl5_<version>/vendor_perl/Ocsinventory/Agent/Modules for Debian like
