### ISSUE TITLE
incorect url in vmware_vcenter plugin 

### ISSUE THREAD

**Issue by wujekbiskup** [PluginsOCSInventory-NG/vmware-vcenter#16]
OCS 2.6 server
php 7
python3.6
Centos7.6

when trying to open for example vm list tab from left menu there is access denied error 

when I'm searching solution I found mistake in url in "function="

wrong url:  http:///ocsreports/index.php?function=vmware&list=VMWARE_VM

corret url: http://<ocsserverurl>/ocsreports/index.php?function=ms_vmware_vcenter&list=VMWARE_VM

**Comment by wujekbiskup** [comment]
I found a solution :D 

in file :
/usr/share/ocsinventory-reports/ocsreports/extensions/vmware_vcenter/ms_vmware_vcenter/class/vmwaredetails.class.php

line 131 - change vmware to ms_vmware_vcenter
 
        echo " ><a href='?function=ms_vmware_vcenter&list=".$value."'>".$key."</a></li>";
       # echo " ><a href='?function=vmware&list=".$value."'>".$key."</a></li>";

That's all

**Comment by gillesdubois** [comment]
Hi,

Thank for your feedback, the release from the 21th of april should fix this behavior.

Regards,
Gilles Dubois.
