### ISSUE TITLE
vmwareVcenter Plugin Deployment on agent is not working

### ISSUE THREAD

**Issue by msds18016** [PluginsOCSInventory-NG/vmware-vcenter#18]
Hello,

I have recently installed the OCS server and OCS-agent  on the same centos server. i am also able to successfully install the Plugins and the tables are also visible on the Dashboard ,The issue is those tables are not populating with the vcenter data. I have also made the necessary Configurations of the agent side as well and placed the Vmware,pm file on below location.
![image](https://user-images.githubusercontent.com/64308843/89488882-944e2d00-d7c2-11ea-8aaf-1d6144c6d92b.png)

Moreover logs are not populating in the logs files therefore we are unable to troubleshoot this issue.  i am not able to see any logs related to plugin initialization and communication to server.

![image](https://user-images.githubusercontent.com/64308843/89489091-1d656400-d7c3-11ea-959a-9f438a2f5811.png)

**Comment by gillesdubois** [comment]
Hi,

Did you populate the modules.conf inside the agent's configuration folder with : 
"Use Ocsinventory::Agent::Modules::Vmware;" 

Also, your VMWare URL is wrong in your file. 
Use the API's root URI.

Regards,
Gilles Dubois.
