### ISSUE TITLE
[vmware] Can't auth with the sevrer

### ISSUE THREAD

**Issue by ghost** [PluginsOCSInventory-NG/vmware-vcenter#3]
Please Can you confirm the correct syntax for log in to the Vcenter Server.

URL ?
https://domain_name/vsphere-client/
https://domain_name
domain_name
https://ip/vsphere-client/
https://ip
ip

AUTH ?
'username@domain:password' | base64
'username@domain + password' | base64
'username@domain+password' | base64
'username@domainpassword' | base64

PS: [vmware] Can't auth with the sevrer <- Please correct this word

**Comment by gillesdubois** [comment]
Hi,

I clarified the user pass combo in base 64 in the Readme.md file.
The url itself is the root url (https).

For example : 
- https://myvcenterserver/

Note : don't forget to put the last "/" or it won't work.

You can checkout the readme here : 
https://github.com/PluginsOCSInventory-NG/vmware-vcenter/blob/master/README.md

Regards,
Gilles Dubois.

**Comment by ekip-94** [comment]
Du coup c'est comment pour l'auth ?? On écrit ça comment ??

**Comment by gillesdubois** [comment]
Bonjour,

Prenez le temps de lire le ReadMe, celui-ci donne l'information.
https://github.com/PluginsOCSInventory-NG/vmware-vcenter/blob/master/README.md

Cdlt,
Gilles Dubois.

**Comment by ghost** [comment]
Salut aze789,

J'utilise mon petit script bash en sortie tu as la valeur à mettre dans le fichier de conf.

#!/bin/bash
username=toto
password=toto
credentials="$(echo -n "$username:$password" | base64)"
echo $credentials

N'oublie pas de donner à l'utilisateur le read dans Vcenter.

**Comment by ekip-94** [comment]
justement je vient de le lire et cela ne fonctionne pas.

J'ai essayer en base 64 puis en normal
usr:mdp
usr : mdp
usr+mdp
usr + mdp

**Comment by ekip-94** [comment]
@Ujishi je le met ou ton fichier bash ?? (dsl si c'est une question con je suis nul en linux :/ )

**Comment by ghost** [comment]
@aze789 tu créais un fichier sh dans un répertoire utilisateur comme ton home...
