### ISSUE TITLE
Error with agent module

### ISSUE THREAD

**Issue by fedaya** [PluginsOCSInventory-NG/vmware-vcenter#4]
Hi,
I tried to use the VMWare Agent Module.
When I launch ocsinventory-agent, I have this error:
`Can't encode a value of type: JSON::PP::Boolean at /usr/local/share/perl/5.24.1/Ocsinventory/Agent/XML/Inventory.pm line 108.`

I modified a bit the Vmware.pm file in order to have a really more verbose debug log output, showing every JSON Return using Data::Dumper.
There are indeed many JSON::PP::Boolean that XMLOut can't seem to process, such as in this example:
```
                        'cdroms' => [
                                     {
                                       'value' => {
                                                    'ide' => {
                                                               'primary' => bless( do{\(my $o = 0)}, 'JSON::PP::Boolean' ),
                                                               'master' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' )
                                                             },

```

I run it on Debian 9 with ocsinventory agent 2.3.1 and perl 5.24.1. (I downloaded the plugin zip from ocs plugin repository)
I run a VMWare vSphere vCenter v6.5.0 appliance.

**Comment by erebus04** [comment]
I have the same Problem on CentOS 7

**Comment by szrobag** [comment]
Hello, same problem here on Debian 9, OCS 2.5 and perl 5.24.1.

**Comment by petyakoma** [comment]
exactly the same error message here:

`Can't encode a value of type: JSON::PP::Boolean at /usr/local/share/perl/5.24.1/Ocsinventory/Agent/XML/Inventory.pm line 108.`

VMWare vSphere 6.7.0 / Debian 9 / OCS 2.5

**Comment by 0XD1B** [comment]
Did someone found a way to fix this issue ? I'm facing the same problem...
VMWare vSphere 6.5 / Centos 7.6 / OCS agent 2.4.2 / perl v5.16.3

**Comment by 0XD1B** [comment]
Found a fix for my case, a boolean wasn't convert to string in the json generation part. The problem was from the vmware.pm agent file at line 297 :
```
--- Original line ---
EFI_LEGACY_BOOT => [$vm_infos_details->{'value'}->{'boot'}->{'efi_legacy_boot'}],
--- Should become ---
EFI_LEGACY_BOOT => [manage_json_pp_bool($vm_infos_details->{'value'}->{'boot'}->{'efi_legacy_boot'})],
```

**Comment by pchamo** [comment]
You are a genius and I'm lucky. It works for me :) Thank you!

**Comment by 0XD1B** [comment]
Glad that helped you :)

**Comment by fbomj** [comment]
Fix => https://github.com/PluginsOCSInventory-NG/vmware-vcenter/pull/13
