### ISSUE TITLE
OCSReports 2.4.1

### ISSUE THREAD

**Issue by ghost** [PluginsOCSInventory-NG/vmware-vcenter#5]
Hi,

I will try to use your plugin with OCSReports 2.4.1 but when the agent send the inventory file with Vmware.pm nothing adds on the database server ? Do you have any idea ?

Thanks.

**Comment by fbomj** [comment]
Hi,
Is 'Vmware.pm' stored in the correct directory (depending of your linux distribution). It should be stored in .../Agent/Modules/ directory. Please verify.
Regards
