### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ekip-94** [PluginsOCSInventory-NG/vmware-vcenter#7]
Bonjour,
Je voudrais installer le plugin VmWare - Vcenter mais lorsque j'essaye d'installer le lugin sur la console OCS celle-ci me dit que le plugin est deja installer or je ne le trouve dans aucun dossier. une explicaion à cela ??

**Comment by ghost** [comment]
Tu es à la version 2.4.1 ?

**Comment by ekip-94** [comment]
Nn j'ai la 2.4 tout court
