### ISSUE TITLE
Access denied when trying to access detail page

### ISSUE THREAD

**Issue by interceptor49** [PluginsOCSInventory-NG/vmware-vcenter#9]
Hello,
Every time I tried to access the different detail page of the plugin, such as "datastore list" or "Vm list" I got "Access Denied".

Error is coming from the function parameter which doesn't match the extension name

https://dl.plik.ovh/file/mYsqk7RmCIAHsv70/hGCkeBlkHFoK8Y7i/2019-07-11-115233_1757x134_scrot.png

https://dl.plik.ovh/file/Sd1FJulH65ltdRnH/Gi09UHDlivfyHkSr/2019-07-11-115239_491x26_scrot.png

https://dl.plik.ovh/file/GJXfK1HU1G4459UM/KmWv5Z4HriUfhlAm/2019-07-11-115321_161x316_scrot.png

I'll submit a PR with the fix, if someone could review it and prod it if it's consistent.

Thanks

**Comment by interceptor49** [comment]
apparently I cannot submit branch.
Find attached the diff
[diff.txt](https://github.com/PluginsOCSInventory-NG/vmware-vcenter/files/3381440/diff.txt)

Thanks

**Comment by Sol-hu** [comment]
I had the same problem “ACCESS DENIED”，Have you found a solution

**Comment by Sol-hu** [comment]
> I had the same problem “ACCESS DENIED”，Have you found a solution

My vCenter Version "6.7"

**Comment by Sol-hu** [comment]
> Hello,
> Every time I tried to access the different detail page of the plugin, such as "datastore list" or "Vm list" I got "Access Denied".
> 
> Error is coming from the function parameter which doesn't match the extension name
> 
> https://dl.plik.ovh/file/mYsqk7RmCIAHsv70/hGCkeBlkHFoK8Y7i/2019-07-11-115233_1757x134_scrot.png
> 
> https://dl.plik.ovh/file/Sd1FJulH65ltdRnH/Gi09UHDlivfyHkSr/2019-07-11-115239_491x26_scrot.png
> 
> https://dl.plik.ovh/file/GJXfK1HU1G4459UM/KmWv5Z4HriUfhlAm/2019-07-11-115321_161x316_scrot.png
> 
> I'll submit a PR with the fix, if someone could review it and prod it if it's consistent.
> 
> Thanks

hello，Has this problem been solved?

**Comment by pchamo** [comment]
It solved the issue for me too :) Thank you.
